trailingComma: "es5"
useTabs: false
tabWidth: 2
semi: true
singleQuote: false
endOfLine: lf
printWidth: 80
singleAttributePerLine: true
plugins: [prettier-plugin-tailwindcss]
tailwindConfig: "./tailwind.config.cjs"
